steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['run', '-e', 'CI=true', 'eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA', 'npm', 'test', '--', '--coverage']
images:
    - 'eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
substitutions:
    _REGION: europe-west4
    _SERVICE_NAME: sg-calculator-test