steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA']
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
        - 'run'
        - 'deploy'
        - '${_SERVICE_NAME}'
        - '--image'
        - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
        - '--region'
        - '${_REGION}'
        - '--platform'
        - 'managed'
images:
    - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
substitutions:
    _REGION: europe-west4
    _SERVICE_NAME: sg-calculator-test