steps:
    - name: node:alpine
      entrypoint: npm
      args: ['install']
    - name: node:alpine
      entrypoint: npm
      args: ['test', '--', '--coverage', '--watchAll=false']
    - name: node:alpine
      entrypoint: npm
      args: ['run', 'build']