steps:
    - name: node:alpine
      entrypoint: npm
      args: ['install']
    - name: node:alpine
      entrypoint: npm
    - name: node:alpine
      entrypoint: npm
      args: ['test']
    - name: node:alpine
      entrypoint: npm
      args: ['run', 'build']