steps:
    - name: 'gcr.io/cloud-builders/node'
      entrypoint: npm
      args: ['install']
    - name: 'gcr.io/cloud-builders/node'
      entrypoint: npm
    - name: 'gcr.io/cloud-builders/node'
      entrypoint: npm
      args: ['test']
    - name: 'gcr.io/cloud-builders/node'
      entrypoint: npm
      args: ['run', 'build']
    