steps:
    # build the container image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/sg-calculator-test:$COMMIT_SHA', '.']
    # push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/sg-calculator-test:$COMMIT_SHA']
    # Deploy container image to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
      - 'run'
      - 'deploy'
      - 'sg-calculator-test'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sg-calculator-test:$COMMIT_SHA'
      - '--region'
      - 'europe-west4'
      - '--platform'
      - 'managed'
    images:
    - 'gcr.io/$PROJECT_ID/sg-calculator-test:$COMMIT_SHA'
    options:
        env:
        - 'REGION=europe-west4'
        - 'SERVICE_NAME=sg-calculator-test' 